import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ReactNode} from "react";
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
  return (
    <html lang="en">
      {/* page.tsx render here */}
      <body className={inter.className}>
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <main>{children}</main>
      </body>
    </html>
  )
}
